# helm upgrade --cleanup-on-fail \
#   --install ztjh-release jupyterhub/jupyterhub \
#   --namespace ztjh \
#   --create-namespace \
#   --version=2.0.0 \
#   --values config.yaml

# helm upgrade --cleanup-on-fail \
#   ztjh-release jupyterhub/jupyterhub \
#   --namespace ztjh \
#   --version=2.0.0 \
#   --values config.yaml

hub:
  config:
    Authenticator:
      admin_users:
        - admin
  allowNamedServers: true

singleuser:
  startTimeout: 60
  image:
    name: nmearl/cds-jsp
    tag: "0.1.2"

# scheduling:
#   userScheduler:
#     enabled: false